### PR TITLE
add ocean and load tide correction programs

### PR DESCRIPTION
**Pull request by tsutterley**
Should hopefully be working with your format @fspaolo

### CODE REVIEW

**Comment by dshean** [comment]
This looks great @tsutterley!

**Comment by fspaolo** [comment]
Sorry Tyler, I missed this... will take a look at it

**Review by fspaolo — CHANGES_REQUESTED** [review]
Tyler, can you please add a small README.md file with Credits to you and the disclamer pointing to the original sources?

**Comment by tsutterley** [comment]
how's that @fspaolo?

**Review by fspaolo — APPROVED** [review]
Merging the code as it is fully independent. We can workout needed modifications as we turn the repo into a package.

**Pull request merged**
